from __future__ import annotations

import hashlib


def hash_password(password: str) -> str:
    return hashlib.sha256(password.encode("utf-8")).hexdigest()


ROLE_LABELS = {
    "student": "Студент",
    "teacher": "Преподаватель",
    "administrator": "Администратор",
}

DAY_ORDER = {
    "Понедельник": 1,
    "Вторник": 2,
    "Среда": 3,
    "Четверг": 4,
    "Пятница": 5,
    "Суббота": 6,
}

PAIR_TIMES = {
    1: "08:30-10:10",
    2: "10:20-12:00",
    3: "12:20-14:00",
    4: "14:10-15:50",
    5: "16:00-17:40",
}

STUDENTS = [
    {
        "id": 1,
        "full_name": "Смирнова Елена Андреевна",
        "group": "ИДБ-23-13",
        "record_book": "23-13-001",
        "course": 3,
        "program": "Информационные системы и технологии",
        "study_form": "Очная",
        "funding": "Бюджет",
        "status": "Обучается",
    },
    {
        "id": 2,
        "full_name": "Кузнецов Артем Сергеевич",
        "group": "ИДБ-23-13",
        "record_book": "23-13-002",
        "course": 3,
        "program": "Информационные системы и технологии",
        "study_form": "Очная",
        "funding": "Контракт",
        "status": "Обучается",
    },
    {
        "id": 3,
        "full_name": "Орлова Мария Дмитриевна",
        "group": "ИДБ-23-14",
        "record_book": "23-14-003",
        "course": 3,
        "program": "Информационные системы и технологии",
        "study_form": "Очная",
        "funding": "Бюджет",
        "status": "Обучается",
    },
    {
        "id": 4,
        "full_name": "Федоров Илья Павлович",
        "group": "ИДБ-23-14",
        "record_book": "23-14-004",
        "course": 3,
        "program": "Информационные системы и технологии",
        "study_form": "Очная",
        "funding": "Контракт",
        "status": "Академический отпуск",
    },
]

TEACHERS = [
    {
        "id": 1,
        "full_name": "Иванов Виктор Викторович",
        "department": "Кафедра информационных систем",
        "position": "Доцент",
        "degree": "к.т.н.",
        "email": "ivanov@vdekanat.local",
        "phone": "79000000001",
        "subjects": ["Информационные системы", "Базы данных"],
    },
    {
        "id": 2,
        "full_name": "Козлова Марина Игоревна",
        "department": "Кафедра информационных систем",
        "position": "Старший преподаватель",
        "degree": "без степени",
        "email": "kozlova@vdekanat.local",
        "phone": "79000000002",
        "subjects": ["Web-технологии", "Программирование"],
    },
    {
        "id": 3,
        "full_name": "Сидоров Илья Игоревич",
        "department": "Кафедра прикладной математики",
        "position": "Профессор",
        "degree": "д.т.н.",
        "email": "sidorov@vdekanat.local",
        "phone": "79000000003",
        "subjects": ["Дискретная математика"],
    },
]

USERS = {
    "student_demo": {
        "password_hash": hash_password("stud2026"),
        "role": "student",
        "full_name": "Смирнова Елена Андреевна",
        "student_id": 1,
        "teacher_id": None,
        "is_active": True,
        "last_password_change": "2026-04-01",
    },
    "student_kuznetsov": {
        "password_hash": hash_password("kuz2026"),
        "role": "student",
        "full_name": "Кузнецов Артем Сергеевич",
        "student_id": 2,
        "teacher_id": None,
        "is_active": True,
        "last_password_change": "2026-04-05",
    },
    "teacher_demo": {
        "password_hash": hash_password("teach2026"),
        "role": "teacher",
        "full_name": "Иванов Виктор Викторович",
        "student_id": None,
        "teacher_id": 1,
        "is_active": True,
        "last_password_change": "2026-03-29",
    },
    "teacher_kozlova": {
        "password_hash": hash_password("koz2026"),
        "role": "teacher",
        "full_name": "Козлова Марина Игоревна",
        "student_id": None,
        "teacher_id": 2,
        "is_active": True,
        "last_password_change": "2026-04-10",
    },
    "admin_demo": {
        "password_hash": hash_password("admin2026"),
        "role": "administrator",
        "full_name": "Новикова Наталья Михайловна",
        "student_id": None,
        "teacher_id": None,
        "is_active": True,
        "last_password_change": "2026-04-12",
    },
}

SCHEDULE_DATA = [
    {
        "day": "Понедельник",
        "pair": 1,
        "time": PAIR_TIMES[1],
        "group": "ИДБ-23-13",
        "subject": "Информационные системы",
        "teacher_id": 1,
        "room": "А-201",
        "lesson_type": "Лекция",
        "format": "Очная",
    },
    {
        "day": "Понедельник",
        "pair": 3,
        "time": PAIR_TIMES[3],
        "group": "ИДБ-23-13",
        "subject": "Web-технологии",
        "teacher_id": 2,
        "room": "В-307",
        "lesson_type": "Лабораторная",
        "format": "Очная",
    },
    {
        "day": "Вторник",
        "pair": 2,
        "time": PAIR_TIMES[2],
        "group": "ИДБ-23-13",
        "subject": "Базы данных",
        "teacher_id": 1,
        "room": "Б-104",
        "lesson_type": "Лабораторная",
        "format": "Очная",
    },
    {
        "day": "Среда",
        "pair": 1,
        "time": PAIR_TIMES[1],
        "group": "ИДБ-23-13",
        "subject": "Дискретная математика",
        "teacher_id": 3,
        "room": "А-115",
        "lesson_type": "Лекция",
        "format": "Очная",
    },
    {
        "day": "Четверг",
        "pair": 4,
        "time": PAIR_TIMES[4],
        "group": "ИДБ-23-13",
        "subject": "Программирование",
        "teacher_id": 2,
        "room": "В-210",
        "lesson_type": "Практика",
        "format": "Дистанционная",
    },
    {
        "day": "Понедельник",
        "pair": 2,
        "time": PAIR_TIMES[2],
        "group": "ИДБ-23-14",
        "subject": "Информационные системы",
        "teacher_id": 1,
        "room": "А-201",
        "lesson_type": "Лекция",
        "format": "Очная",
    },
    {
        "day": "Среда",
        "pair": 3,
        "time": PAIR_TIMES[3],
        "group": "ИДБ-23-14",
        "subject": "Web-технологии",
        "teacher_id": 2,
        "room": "В-307",
        "lesson_type": "Лабораторная",
        "format": "Очная",
    },
    {
        "day": "Пятница",
        "pair": 2,
        "time": PAIR_TIMES[2],
        "group": "ИДБ-23-14",
        "subject": "Дискретная математика",
        "teacher_id": 3,
        "room": "А-115",
        "lesson_type": "Практика",
        "format": "Очная",
    },
]

GRADE_RECORDS = [
    {
        "id": 1,
        "student_id": 1,
        "teacher_id": 1,
        "subject": "Информационные системы",
        "group": "ИДБ-23-13",
        "semester": "2026 весна",
        "control_type": "Экзамен",
        "attempt": 1,
        "m1": 24,
        "m2": 25,
        "points": 49,
        "coefficient": 2.8,
        "date": "2026-04-16",
        "status": "Подтверждена",
    },
    {
        "id": 2,
        "student_id": 1,
        "teacher_id": 1,
        "subject": "Базы данных",
        "group": "ИДБ-23-13",
        "semester": "2026 весна",
        "control_type": "Лабораторная работа",
        "attempt": 1,
        "m1": 23,
        "m2": 23,
        "points": 46,
        "coefficient": 2.1,
        "date": "2026-04-12",
        "status": "Подтверждена",
    },
    {
        "id": 3,
        "student_id": 1,
        "teacher_id": 2,
        "subject": "Web-технологии",
        "group": "ИДБ-23-13",
        "semester": "2026 весна",
        "control_type": "Зачет",
        "attempt": 1,
        "m1": 22,
        "m2": 22,
        "points": 44,
        "coefficient": 2.4,
        "date": "2026-04-17",
        "status": "Подтверждена",
    },
    {
        "id": 4,
        "student_id": 2,
        "teacher_id": 1,
        "subject": "Информационные системы",
        "group": "ИДБ-23-13",
        "semester": "2026 весна",
        "control_type": "Экзамен",
        "attempt": 1,
        "m1": 20,
        "m2": 21,
        "points": 41,
        "coefficient": 2.8,
        "date": "2026-04-16",
        "status": "Подтверждена",
    },
    {
        "id": 5,
        "student_id": 2,
        "teacher_id": 2,
        "subject": "Программирование",
        "group": "ИДБ-23-13",
        "semester": "2026 весна",
        "control_type": "Практика",
        "attempt": 2,
        "m1": 18,
        "m2": 20,
        "points": 38,
        "coefficient": 1.6,
        "date": "2026-04-18",
        "status": "Пересдача",
    },
    {
        "id": 6,
        "student_id": 3,
        "teacher_id": 1,
        "subject": "Информационные системы",
        "group": "ИДБ-23-14",
        "semester": "2026 весна",
        "control_type": "Экзамен",
        "attempt": 1,
        "m1": 25,
        "m2": 25,
        "points": 50,
        "coefficient": 2.8,
        "date": "2026-04-14",
        "status": "Подтверждена",
    },
    {
        "id": 7,
        "student_id": 3,
        "teacher_id": 2,
        "subject": "Web-технологии",
        "group": "ИДБ-23-14",
        "semester": "2026 весна",
        "control_type": "Зачет",
        "attempt": 1,
        "m1": 23,
        "m2": 24,
        "points": 47,
        "coefficient": 2.4,
        "date": "2026-04-15",
        "status": "Подтверждена",
    },
    {
        "id": 8,
        "student_id": 4,
        "teacher_id": 3,
        "subject": "Дискретная математика",
        "group": "ИДБ-23-14",
        "semester": "2026 весна",
        "control_type": "Экзамен",
        "attempt": 1,
        "m1": 0,
        "m2": 0,
        "points": 0,
        "coefficient": 2.5,
        "date": "2026-04-10",
        "status": "Неявка",
    },
]

GRADE_AUDIT = [
    {
        "grade_id": 5,
        "changed_by": "teacher_kozlova",
        "old_value": 32,
        "new_value": 38,
        "changed_at": "2026-04-18 14:20",
        "comment": "Пересдача после доработки практики",
    },
    {
        "grade_id": 8,
        "changed_by": "admin_demo",
        "old_value": 22,
        "new_value": 0,
        "changed_at": "2026-04-10 18:00",
        "comment": "Статус изменен на неявку по заявлению деканата",
    },
]
